name: MSBuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: ./SharpDecryptPwd.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild ${{env.SOLUTION_FILE_PATH}} -t:rebuild -property:Configuration=${{env.BUILD_CONFIGURATION}}

      - name: Package
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Compress-Archive -Path .\revive_hypereal -Destination prebuild_driver.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: prebuild_driver
          name: Release ${{ github.sha }}
          body: 由提交${{ github.sha }}自动触发编译生成的Release。
          draft: false
          prerelease: false
          files: |
            prebuild_driver.zip
