name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # 触发条件：推送符合语义版本号格式的标签（例如 v1.0.0）

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # 替换为你的项目需要的 .NET SDK 版本

      - name: Restore dependencies
        run: dotnet restore SharpDecryptPwd.sln

      - name: Build
        run: dotnet build SharpDecryptPwd.sln -c Release

      - name: Package
        run: dotnet pack SharpDecryptPwd.sln -c Release --output ./nupkgs

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release of version ${{ github.ref }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nupkgs/SharpDecryptPwd.*.nupkg
          asset_name: SharpDecryptPwd.nupkg
          asset_content_type: application/zip
