name: Build SharpDecryptPwd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install .NET Framework 4.0 Developer Pack
        run: |
          Invoke-WebRequest -Uri https://download.visualstudio.microsoft.com/download/pr/3e5c68e7-cd6d-4eeb-b4e8-4b1b9d8b5ad1/4b1e9c3b1818cc8c0df2d9cf53597d18/NetFx4.8.1_DeveloperPack.exe -OutFile NetFx4.8.1_DeveloperPack.exe
          Start-Process -FilePath .\NetFx4.8.1_DeveloperPack.exe -ArgumentList "/quiet", "/norestart" -NoNewWindow -Wait

      - name: Restore dependencies
        run: dotnet restore SharpDecryptPwd.sln

      - name: Build
        run: dotnet build SharpDecryptPwd.sln -c Release

      - name: Run tests (optional)
        run: dotnet test SharpDecryptPwd.sln --logger trx
